# Generated by Django 5.1 on 2024-09-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
