# Generated by Django 5.1 on 2024-09-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_notifications_profile_privacy_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='privacy_policy',
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
