# Generated by Django 5.1 on 2024-09-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_notifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
    ]
