# Generated by Django 5.1 on 2024-09-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_cover_image_subtitle_articleimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlevideo',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='image_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='article_videos/'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
        migrations.DeleteModel(
            name='ArticleVideo',
        ),
    ]
